[workspace]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "community"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
preview = "myst start"
render = "myst build --html"

[dependencies]
mystmd = ">=1.7.0,<2"
python = ">=3.14.2,<3.15"
pandas = ">=2.3.3,<3"
feedgen = ">=1.0.0,<2"
pyyaml = ">=6.0.3,<7"
